
language: python

dist: trusty
sudo: required
group: edge

python:
  - "3.4"

cache:
  directories:
    - $HOME/.cache/pip

script:
  - export PYTHONPATH=`pwd`
  - cd test_project; coverage run manage.py test

after_script:
  - cd test_project; coveralls
