
language: python

dist: trusty
sudo: required
group: edge

python:
  - "3.4"

cache:
  directories:
    - $HOME/.cache/pip

script:
  - export PYTHONPATH=.:..
  - coverage run test_project/manage.py test hotels
  - coverage report
  - coveralls
